version: "3.9"

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8000"
    restart: always
