# Generated by Django 5.0.1 on 2024-01-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_sessao_app_usuario_sessao_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sessao_app',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sessao_site',
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
