# Generated by Django 5.0.1 on 2024-01-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_sessao_app_remove_usuario_sessao_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='token',
            new_name='token_acesso',
        ),
    ]
