# Generated by Django 5.0.1 on 2024-01-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_token_usuario_token_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='token_acesso',
        ),
    ]
